### PR TITLE
fix executor rejection crash, fix duplicate zip entries crash

### PR DESCRIPTION
**Pull request by Bixilon**
The title tells you. I mentioned the problem in #1 

Thanks

Moritz

### CODE REVIEW

**Comment by HeartPattern** [comment]
Can you post any example that produce crash?

**Comment by Bixilon** [comment]
Sure,

In https://files.player.to/tmp/tiny-remapper-0.3.1-fat-player.jar is a module-info.class. It tried to add this file to the output a couple of times, and every time it adds the duplicate, it crashes a thread.

The second one always happens, you shutdown both executors, but the first executor adds tasks to the second one. So you have to first shutdown the first executor, wait until it's down and then stop the second one.

**Comment by HeartPattern** [comment]
I don't have enough knowledge about java9's module systems, but it is weird that one jar contains multiple module-info.java entry. 
Not only for module-info.java, same entry in output jar file is abnormal situation so implicitly ignore it can be dangerous.
I think it would be better to add option to exclude specific file from process like, `--exclude=input:**/module-info.jar` in form of `--exclude=((input|output):(ant pattern))*`.
Can you work for it, or should I do it?

**Comment by HeartPattern** [comment]
It is weird that original jar contains duplicated entry, but I think Exhibitionism should respect original jar file structure. 
Of course, this is not clear solution, but use following method to add duplicated entry to output jar seems better for me.
https://stackoverflow.com/questions/39958486/java-create-a-zip-file-with-duplicate-entries

**Comment by Bixilon** [comment]
Also don't know much about the module system in 9+. Never used it. 

Just thought, it's a temporary fix. A warning would be much better, But re-adding them duplicated is maybe the better solution, but it goes into the illegal direction. Why should we re-add them? The zip seems to "be broken", and should be automatically corrected. But I agree, maybe a start parameter `--fixDuplicates=true`. If not present, it just crashes with a error message Otherwise it should send out a warning. What do you think about this?

**Comment by HeartPattern** [comment]
I agree with you. Will you PR it, or should I work for it?

**Comment by Bixilon** [comment]
Done, also using maximum  system threads now for --parallel

**Comment by HeartPattern** [comment]
Manually rebase commit. Thanks for contribution.

**Pull request closed without merging**
